spring.application.name=bff-agendador-tarefas
usuario.url=${USER_URL}
agendador-tarefas.url=${AGENDADOR_URL}
notificacao.url=${NOTIFICACAO_URL}
cron.horario=${CRON_HOUR}
usuario.email=${USER_MAIL}
usuario.senha=${USER_PASSWORD}
server.port=8083