usuario.url=localhost:8080/usuario
agendador-tarefas.url=http://localhost:8081/agendador-tarefas
notificacao.url=http://localhost:8082/email
cron.horario=${CRON_HOUR:0 0/5 * * * *}
usuario.email=${MAIL_USERNAME:test@example.com}
usuario.senha=${MAIL_PASSWORD:dummy}
server.port=8083