usuario.url=localhost:8080/usuario
agendador-tarefas.url=http://localhost:8081/agendador-tarefas
notificacao.url=http://localhost:8082/email
cron.horario=${CRON_HOUR}
usuario.email=${MAIL_USERNAME}
usuario.senha=${MAIL_PASSWORD}
server.port=8083